API_ID = Config.API_ID
API_HASH = Config.API_HASH
BOT_TOKEN = Config.BOT_TOKEN

WASABI_ACCESS_KEY = Config.WASABI_ACCESS_KEY
WASABI_SECRET_KEY = Config.WASABI_SECRET_KEY
WASABI_BUCKET = Config.WASABI_BUCKET
WASABI_REGION = Config.WASABI_REGION

STORAGE_CHANNEL_ID = Config.STORAGE_CHANNEL_ID
MAX_FILE_SIZE = Config.MAX_FILE_SIZE
FILES_DB = Config.FILES_DB
